In [1]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, 
# the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [185]:
import numpy as np

In [186]:
def vandermonde_matrix():
    
    vector_count = int(input("Enter the number of vector elements: "))

    vector = []
    
    # Creating the vector using the inputs given
    for num in range(vector_count):
        vector_element = int(input(f"Enter element no {num+1}:  "))
        vector.append(vector_element)

    x = np.array(vector).reshape(vector_count,-1) # Reshaping the vector into column vector

    n_columns = int(input("\nEnter the number of columns required: "))

    result = pow(x,0) # Initializing first column of the Vandermonde matrix
    
    # Creating the Vandermonde matrix from the vector
    for i in range(1,n_columns):
        column_matrix = pow(x,i)
        result = np.concatenate((result, column_matrix), axis=1)
    
    print("\n\nThe Vandermonde matrix for the given input is:\n", '-'*44,"\n\n", result)

In [187]:
vandermont_matrix()

Enter the number of vector elements: 3
Enter element no 1:  21
Enter element no 2:  22
Enter element no 3:  23

Enter the number of columns required: 4


The Vandermonde matrix for the given input is:
 -------------------------------------------- 

 [[    1    21   441  9261]
 [    1    22   484 10648]
 [    1    23   529 12167]]


In [188]:
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is 
# defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.

# Question: Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [192]:
def moving_average(arr):
    
    window = int(input('Enter the moving average window size: '))

    sequence = []

    for i in range(len(arr)-window+1):
        sequence.append(round(((arr[i:i+3]).mean()),2))

    sequence = np.array(sequence)
    
    print(f"\nThe moving average sequence for the given window size \"{window}\" is: \n","-"*59
          ,"\n\n", sequence)

In [193]:
array1 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [194]:
moving_average(array1)

Enter the moving average window size: 3

The moving average sequence for the given window size "3" is: 
 ----------------------------------------------------------- 

 [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
